In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Load pickled data
import pickle
import matplotlib.pyplot as plt

# TODO: Fill this in based on where you saved the training and testing data

training_file = "test.p"
validation_file="valid.p"
testing_file = "train.p"

with open(training_file, mode='rb') as f:
    train = pickle.load(f)
with open(validation_file, mode='rb') as f:
    valid = pickle.load(f)
with open(testing_file, mode='rb') as f:
    test = pickle.load(f)
    
X_train, y_train = train['features'], train['labels']
X_valid, y_valid = valid['features'], valid['labels']

X_test, y_test = test['features'], test['labels']

In [3]:
import numpy as np
print('train='+str(X_train.shape))
print('test='+str(X_test.shape))
print('validate='+str(X_valid.shape))
# print(X_train.shape)
train_shape=X_train.shape
test_shape=X_test.shape
valid_shape=X_valid.shape
labels_number=len(np.unique(y_train))
labels_number

train=(12630, 32, 32, 3)
test=(34799, 32, 32, 3)
validate=(4410, 32, 32, 3)


43

In [4]:
##Normalisation
X_train=X_train/255.0
X_test=X_test/255.0
X_valid=X_valid/255.0


In [5]:
import tensorflow as tf
from tensorflow import estimator,metrics,sigmoid,acos
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,MaxPool2D,Dropout,Flatten,Conv2D
from tensorflow.keras.activations import relu

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout

In [6]:
def build_models(hp):
    model=Sequential([
        Conv2D(
            filters=hp.Int('conv_1_filter',min_value=32,max_value=128,step=16),
            kernel_size=hp.Choice('conv_1_kernel',values=[3,5]),
            activation='relu',
            input_shape=(32,32,3)
        ),
        Dropout(hp.Choice('d1',values=[1e-2,1e-3])),
        
        Conv2D(filters=hp.Int('conv_2_filter',min_value=32,max_value=64,step=16),
               kernel_size=hp.Choice('conv_2_kernel',values=[3,5]),
               activation='relu'
        ),
        Dropout(hp.Float('d2',min_value=1e-3,max_value=1e-1)),

        Conv2D(filters=hp.Int('conv_2_filter',min_value=32,max_value=64,step=16),
               kernel_size=hp.Choice('conv_2_kernel',values=[3,5]),
               activation='relu'
        ),
        Conv2D(filters=hp.Int('conv_3_filter',min_value=32,max_value=128,step=16),kernel_size=(3,3),padding="same", activation="relu"),
        MaxPool2D(pool_size=(2,2),strides=(2,2)),
        Conv2D(filters=hp.Int('conv_4_filter',min_value=32,max_value=256,step=16),kernel_size=(3,3),padding="same", activation="relu"),
        MaxPool2D(pool_size=(3,3),strides=(3,3)),
        
        Dense(units=hp.Int('dense_1_units',
              min_value=32,max_value=128,step=8),
              activation='relu'
        ),
        Dropout(hp.Float('d3',min_value=1e-3,max_value=1e-1)),

        Dense(units=hp.Int('dense_4_units',
              min_value=32,max_value=256,step=8),
              activation='relu'
        ),
        
#         Flatten(),
        Dropout(hp.Float('d4',min_value=1e-3,max_value=1e-1)),
        MaxPool2D(pool_size=(3,3),strides=(3,3)),
        Dense(units=hp.Int('dense_5_units',
              min_value=128,max_value=512,step=32),
              activation='relu'
        ),
        
        Dense(43,activation='softmax')
    ])
    model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate',values=[1e-1,1e-3])),
                 loss='sparse_categorical_crossentropy',
                 metrics=['accuracy'])
    return model

In [7]:
from kerastuner import RandomSearch,HyperParameters #importing HyperParamter and RandomSearch

In [15]:
#now using random serch for this model
tuner_search=RandomSearch(build_models,objective='val_accuracy',max_trials=5,directory='output',project_name='Mnist')

In [16]:
#seaching hyper parameters for this using this module i.e modle will do backpropogation,frontpropogation and other 
# stuffs to carry on this model and find best parameter 
tuner_search.search(X_train,y_train,epochs=4,validation_data=(X_valid,y_valid))

Train on 12630 samples, validate on 4410 samples
Epoch 1/4
11744/12630 [==========================>...] - ETA: 9:31 - loss: 3.7597 - accuracy: 0.03 - ETA: 3:17 - loss: 11.4950 - accuracy: 0.041 - ETA: 2:02 - loss: 12.9413 - accuracy: 0.049 - ETA: 1:30 - loss: 13.6331 - accuracy: 0.049 - ETA: 1:12 - loss: 14.0174 - accuracy: 0.048 - ETA: 1:01 - loss: 14.1704 - accuracy: 0.053 - ETA: 53s - loss: 14.2376 - accuracy: 0.060 - ETA: 47s - loss: 14.3876 - accuracy: 0.05 - ETA: 42s - loss: 14.4726 - accuracy: 0.05 - ETA: 39s - loss: 14.5928 - accuracy: 0.05 - ETA: 36s - loss: 14.5942 - accuracy: 0.05 - ETA: 33s - loss: 14.6172 - accuracy: 0.06 - ETA: 31s - loss: 14.6567 - accuracy: 0.06 - ETA: 30s - loss: 14.6157 - accuracy: 0.06 - ETA: 28s - loss: 14.6498 - accuracy: 0.06 - ETA: 27s - loss: 14.6796 - accuracy: 0.06 - ETA: 26s - loss: 14.6446 - accuracy: 0.06 - ETA: 25s - loss: 14.7145 - accuracy: 0.06 - ETA: 24s - loss: 14.7495 - accuracy: 0.06 - ETA: 23s - loss: 14.7680 - accuracy: 0.06 - ETA

Train on 12630 samples, validate on 4410 samples
Epoch 1/4
11744/12630 [==========================>...] - ETA: 9:34 - loss: 3.7640 - accuracy: 0.01 - ETA: 3:20 - loss: 11.1606 - accuracy: 0.056 - ETA: 2:04 - loss: 12.5392 - accuracy: 0.071 - ETA: 1:32 - loss: 13.3458 - accuracy: 0.064 - ETA: 1:14 - loss: 13.9059 - accuracy: 0.053 - ETA: 1:02 - loss: 14.0792 - accuracy: 0.057 - ETA: 54s - loss: 14.2379 - accuracy: 0.058 - ETA: 48s - loss: 14.4550 - accuracy: 0.05 - ETA: 44s - loss: 14.5914 - accuracy: 0.05 - ETA: 40s - loss: 14.6196 - accuracy: 0.05 - ETA: 37s - loss: 14.7383 - accuracy: 0.04 - ETA: 35s - loss: 14.7926 - accuracy: 0.04 - ETA: 33s - loss: 14.8583 - accuracy: 0.04 - ETA: 31s - loss: 14.8770 - accuracy: 0.04 - ETA: 29s - loss: 14.9105 - accuracy: 0.04 - ETA: 28s - loss: 14.9397 - accuracy: 0.04 - ETA: 27s - loss: 14.9806 - accuracy: 0.04 - ETA: 26s - loss: 14.9736 - accuracy: 0.04 - ETA: 25s - loss: 14.9946 - accuracy: 0.04 - ETA: 24s - loss: 15.0523 - accuracy: 0.04 - ETA

Train on 12630 samples, validate on 4410 samples
Epoch 1/4
12630/12630 [==============================] - ETA: 8:49 - loss: 3.7595 - accuracy: 0.01 - ETA: 2:17 - loss: 3.7285 - accuracy: 0.07 - ETA: 1:21 - loss: 3.6997 - accuracy: 0.06 - ETA: 58s - loss: 3.6691 - accuracy: 0.0609 - ETA: 46s - loss: 3.6565 - accuracy: 0.054 - ETA: 39s - loss: 3.6403 - accuracy: 0.059 - ETA: 33s - loss: 3.6096 - accuracy: 0.066 - ETA: 30s - loss: 3.5913 - accuracy: 0.068 - ETA: 27s - loss: 3.5831 - accuracy: 0.066 - ETA: 24s - loss: 3.5840 - accuracy: 0.066 - ETA: 23s - loss: 3.5802 - accuracy: 0.063 - ETA: 21s - loss: 3.5807 - accuracy: 0.067 - ETA: 20s - loss: 3.5660 - accuracy: 0.069 - ETA: 19s - loss: 3.5524 - accuracy: 0.071 - ETA: 18s - loss: 3.5509 - accuracy: 0.072 - ETA: 17s - loss: 3.5550 - accuracy: 0.070 - ETA: 16s - loss: 3.5551 - accuracy: 0.069 - ETA: 15s - loss: 3.5546 - accuracy: 0.067 - ETA: 15s - loss: 3.5589 - accuracy: 0.064 - ETA: 14s - loss: 3.5565 - accuracy: 0.062 - ETA: 14s - lo

Train on 12630 samples, validate on 4410 samples
Epoch 1/4
 9504/12630 [=====================>........] - ETA: 10:01 - loss: 3.7655 - accuracy: 0.056 - ETA: 2:36 - loss: 12.2744 - accuracy: 0.061 - ETA: 1:32 - loss: 13.3461 - accuracy: 0.070 - ETA: 1:13 - loss: 13.7942 - accuracy: 0.065 - ETA: 1:01 - loss: 13.8046 - accuracy: 0.079 - ETA: 50s - loss: 14.1205 - accuracy: 0.073 - ETA: 42s - loss: 14.2952 - accuracy: 0.07 - ETA: 38s - loss: 14.4076 - accuracy: 0.06 - ETA: 35s - loss: 14.5465 - accuracy: 0.06 - ETA: 33s - loss: 14.5737 - accuracy: 0.06 - ETA: 31s - loss: 14.6166 - accuracy: 0.06 - ETA: 29s - loss: 14.6159 - accuracy: 0.06 - ETA: 28s - loss: 14.6153 - accuracy: 0.06 - ETA: 26s - loss: 14.6303 - accuracy: 0.07 - ETA: 24s - loss: 14.7146 - accuracy: 0.06 - ETA: 22s - loss: 14.7591 - accuracy: 0.06 - ETA: 22s - loss: 14.7767 - accuracy: 0.06 - ETA: 21s - loss: 14.8046 - accuracy: 0.06 - ETA: 20s - loss: 14.8474 - accuracy: 0.06 - ETA: 19s - loss: 14.8639 - accuracy: 0.06 - ETA

Train on 12630 samples, validate on 4410 samples
Epoch 1/4
10816/12630 [========================>.....] - ETA: 10:07 - loss: 3.7617 - accuracy: 0.016 - ETA: 3:30 - loss: 11.1598 - accuracy: 0.057 - ETA: 2:10 - loss: 12.8409 - accuracy: 0.053 - ETA: 1:36 - loss: 13.5614 - accuracy: 0.051 - ETA: 1:17 - loss: 13.9616 - accuracy: 0.050 - ETA: 1:05 - loss: 14.0790 - accuracy: 0.058 - ETA: 56s - loss: 14.1215 - accuracy: 0.066 - ETA: 50s - loss: 14.2870 - accuracy: 0.06 - ETA: 45s - loss: 14.3542 - accuracy: 0.06 - ETA: 42s - loss: 14.4339 - accuracy: 0.06 - ETA: 39s - loss: 14.4983 - accuracy: 0.06 - ETA: 36s - loss: 14.5297 - accuracy: 0.06 - ETA: 34s - loss: 14.4754 - accuracy: 0.07 - ETA: 32s - loss: 14.4852 - accuracy: 0.07 - ETA: 30s - loss: 14.5283 - accuracy: 0.07 - ETA: 29s - loss: 14.5496 - accuracy: 0.07 - ETA: 28s - loss: 14.6447 - accuracy: 0.06 - ETA: 27s - loss: 14.6425 - accuracy: 0.07 - ETA: 26s - loss: 14.7087 - accuracy: 0.06 - ETA: 25s - loss: 14.7164 - accuracy: 0.06 - E

INFO:tensorflow:Oracle triggered exit


In [54]:
model=tuner_search.get_best_models(num_models=1)[0]#using to get best model out of this

In [55]:
a=model.predict_classes(X_test)

In [24]:
from sklearn.metrics import accuracy_score

# Here the matrics comes out to be an 3d matrices

In [57]:
a

array([[[42]],

       [[41]],

       [[41]],

       ...,

       [[25]],

       [[25]],

       [[25]]], dtype=int64)

In [59]:
y_test

array([41, 41, 41, ..., 25, 25, 25], dtype=uint8)

In [58]:
y_test.shape

(34799,)

In [43]:
(b)=a

In [45]:
a.shape

(34799, 1, 1)

In [50]:
b=a.ravel()


In [51]:
b

array([42, 41, 41, ..., 25, 25, 25], dtype=int64)

In [52]:
accuracy_score(y_test,b)

0.8466622604097819